name: countries-data

on:
  push:
    branches: [master, dev]

  pull_request: 
    branches: [master, dev]
  
jobs:
  build:
    name: Lint, build, deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Building
        run: npm run build --production
